import { Header, TopLoader } from "@repo/ui";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import LeftFloatingButtons from "../components/floating-left-buttons";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <TopLoader theme="blue" />
        <Header />

        {children}
      </body>
    </html>
  );
}
